name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Don't fetch submodules automatically since we need to set up auth first
          
      - name: Setup SSH key for private submodules
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACCESS_SSH_KEY }}
          
      - name: Initialize and update submodules
        run: |
          git submodule update --init --recursive
          
      - name: Verify submodules and symlinks
        run: |
          echo "=== Checking submodules ==="
          git submodule status
          echo "=== Checking external_docs directory ==="
          ls -la external_docs/
          echo "=== Checking docs/rails/services symlink ==="
          ls -la docs/rails/
          echo "=== Verifying symlink target exists ==="
          if [ -L "docs/rails/services" ]; then
            echo "docs/rails/services is a symbolic link"
            target=$(readlink docs/rails/services)
            echo "Symlink points to: $target"
            if [ -d "docs/rails/services" ]; then
              echo "✓ Symlink target is accessible"
              ls -la docs/rails/services/ | head -5
            else
              echo "✗ Symlink target is NOT accessible"
            fi
          else
            echo "docs/rails/services is not a symbolic link"
            echo "=== Creating symbolic link ==="
            if [ -d "external_docs/rails_services/docs" ]; then
              ln -s ../../external_docs/rails_services/docs docs/rails/services
              echo "✓ Created symbolic link: docs/rails/services -> ../../external_docs/rails_services/docs"
              ls -la docs/rails/services/ | head -5
            else
              echo "✗ Cannot create symlink: external_docs/rails_services/docs does not exist"
              exit 1
            fi
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
        
      - name: Verify build includes symlinked content
        run: |
          echo "=== Checking if build includes rails services docs ==="
          find build/docs/rails/services -type f | head -10
          echo "=== Verifying specific documentation files ==="
          if [ -f "build/docs/rails/services/index.html" ]; then
            echo "✓ Services index page found in build"
          else
            echo "✗ Services index page NOT found in build"
          fi
          if [ -f "build/docs/rails/services/getting-started/index.html" ]; then
            echo "✓ Getting started page found in build"
          else
            echo "✗ Getting started page NOT found in build"
          fi
          echo "=== Total services documentation files built: ==="
          find build/docs/rails/services -type f | wc -l

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
